version: "3.2"

services:
    database:
      image: amsterdam/postgres
      ports:
        - "5402:5432"
      environment:
        POSTGRES_HOST: localhost
        POSTGRES_PASSWORD: insecure
        POSTGRES_DB: cleanstreet
        POSTGRES_USER: cleanstreet

    web:
      build: .
      ports:
        - "8129:80"
      links:
        - database:database
        
      environment:
        SYMFONY__CLEANSTREET__DATABASE_HOST: database
        SYMFONY__CLEANSTREET__DATABASE_PORT: "5432"
        SYMFONY__CLEANSTREET__DATABASE_NAME: "cleanstreet"
        SYMFONY__CLEANSTREET__DATABASE_USER: "cleanstreet"
        SYMFONY__CLEANSTREET__DATABASE_PASSWORD: "insecure"
        SYMFONY__CLEANSTREET__MAILER_TRANSPORT: "smtp"
        SYMFONY__CLEANSTREET__MAILER_HOST: ""
        SYMFONY__CLEANSTREET__MAILER_USER: ""
        SYMFONY__CLEANSTREET__MAILER_PASSWORD: ""
        SYMFONY__CLEANSTREET__MAILER_PORT: "25"
        SYMFONY__CLEANSTREET__MAILER_ENCRYPTION: "null" # null, ssl, tls
        SYMFONY__CLEANSTREET__SECRET: "insecure" # random
        SYMFONY__CLEANSTREET__APP_PHONE_ENABLED: "true"
        SYMFONY__CLEANSTREET__APP_MESSAGEBIRD_KEY: "insecure"
        SYMFONY__CLEANSTREET__PIWIK_SITE_ID: "null" # null for no piwik integration

