version: "3.2"

services:
    database-postgres:
      image: postgres:latest
      expose:
        - "5402:5432"
      environment:
        POSTGRES_PASSWORD: insecure
        
    web:
      build: .
      ports:
        - "80:80"
      links:
        - database-postgres:database
        
      environment:
        SYMFONY__CLEANSTREET__DATABASE_HOST: database
        SYMFONY__CLEANSTREET__DATABASE_PORT: "5432"
        SYMFONY__CLEANSTREET__DATABASE_NAME: "postgres"
        SYMFONY__CLEANSTREET__DATABASE_USER: "postgres"
        SYMFONY__CLEANSTREET__DATABASE_PASSWORD: "insecure"
        SYMFONY__CLEANSTREET__MAILER_TRANSPORT: "smtp"
        SYMFONY__CLEANSTREET__MAILER_HOST: ""
        SYMFONY__CLEANSTREET__MAILER_USER: ""
        SYMFONY__CLEANSTREET__MAILER_PASSWORD: ""
        SYMFONY__CLEANSTREET__MAILER_PORT: "25"
        SYMFONY__CLEANSTREET__MAILER_ENCRYPTION: "null" # null, ssl, tls
        SYMFONY__CLEANSTREET__SECRET: "insecure" # random
        SYMFONY__CLEANSTREET__MAIL_FROM: "service@website-domain"
        SYMFONY__CLEANSTREET__MAIL_CC: "service@website-domain"
        SYMFONY__CLEANSTREET__RETENTION_POLICY: "P14D"
        SYMFONY__CLEANSTREET__REQUEST_CONTEXT_HOST: "website-domain" # domain, scheme and base url for links in e-mails
        SYMFONY__CLEANSTREET__REQUEST_CONTEXT_SCHEME: "https"
        SYMFONY__CLEANSTREET__REQUEST_CONTEXT_BASE_URL: ""
        SYMFONY__CLEANSTREET__MESSAGEBIRD_ENABLE: "false"
        SYMFONY__CLEANSTREET__MESSAGEBIRD_API_KEY: "insecure"
        SYMFONY__CLEANSTREET__SMS_ORGINATOR: "service-name"
        SYMFONY__CLEANSTREET__PIWIK_SITE_ID: "null" # null for no piwik integration
        SYMFONY__CLEANSTREET__TRUSTED_PROXIES: "192.168.0.0/16"